<Project>
    <PropertyGroup>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <RestoreLockedMode Condition="'$(CI)' == 'true'">true</RestoreLockedMode>
        <CollectCoverage>true</CollectCoverage>
        <CoverletOutputFormat>cobertura</CoverletOutputFormat>
        <CoverletOutput>./coverage/coverage.cobertura.xml</CoverletOutput>
    </PropertyGroup>
</Project>
